// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVKEVZ325dojjoA4R37LEOQcASD8xm-A8',
    appId: '1:756251703526:web:1c9d0231b078f9417e6327',
    messagingSenderId: '756251703526',
    projectId: 'studio-7043297205-3aae3',
    authDomain: 'studio-7043297205-3aae3.firebaseapp.com',
    storageBucket: 'studio-7043297205-3aae3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHZvCQNBbb3Z1EGchD3lmVi_e71Nw8c8Y',
    appId: '1:756251703526:android:ce7eb8a7c7a2b0817e6327',
    messagingSenderId: '756251703526',
    projectId: 'studio-7043297205-3aae3',
    storageBucket: 'studio-7043297205-3aae3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDct45FVPqDaJoo8PJHuqfvxiUbqV0xCOg',
    appId: '1:756251703526:ios:363561a54d6850277e6327',
    messagingSenderId: '756251703526',
    projectId: 'studio-7043297205-3aae3',
    storageBucket: 'studio-7043297205-3aae3.firebasestorage.app',
    iosClientId: '756251703526-h8vp252b14cb30rrka2q2gu39e6baeti.apps.googleusercontent.com',
    iosBundleId: 'com.enterprise.attendance.mobileAttendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDct45FVPqDaJoo8PJHuqfvxiUbqV0xCOg',
    appId: '1:756251703526:ios:363561a54d6850277e6327',
    messagingSenderId: '756251703526',
    projectId: 'studio-7043297205-3aae3',
    storageBucket: 'studio-7043297205-3aae3.firebasestorage.app',
    iosClientId: '756251703526-h8vp252b14cb30rrka2q2gu39e6baeti.apps.googleusercontent.com',
    iosBundleId: 'com.enterprise.attendance.mobileAttendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjZgfRNPxMpPy2zi2o1jcy6ikagG4J-Jk',
    appId: '1:756251703526:web:7e3d532da0130e927e6327',
    messagingSenderId: '756251703526',
    projectId: 'studio-7043297205-3aae3',
    authDomain: 'studio-7043297205-3aae3.firebaseapp.com',
    storageBucket: 'studio-7043297205-3aae3.firebasestorage.app',
  );
}
